data_demo:
  outputs:
    dev:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}" 
      database: "{{ env_var('SNOWFLAKE_DB') }}" 
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      schema: DBT_UDAVIDDDATA
      threads: 6
      type: snowflake
      user: "{{ env_var('SNOWFLAKE_USER') }}" 
      warehouse: COMPUTE_WH
      private_key:  "{{ env_var('SNOWFLAKE_PRIVATE_KEY') }}" 
      private_key_passphrase: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PASSPHRASE') }}"
      authenticator: username_password_mfa
  target: dev
