data_demo:
  outputs:
    dev:
      account: "{{ var('SNOWFLAKE_ACCOUNT') }}" 
      database: "{{ var('SNOWFLAKE_DB') }}" 
      password: "{{ var('SNOWFLAKE_PASSWORD') }}" 
      role: "{{ var('SNOWFLAKE_ROLE') }}"
      schema: DBT_UDAVIDDDATA
      threads: 6
      type: snowflake
      user: "{{ var('SNOWFLAKE_USER') }}" 
      warehouse: COMPUTE_WH
      authenticator: username_password_mfa
  target: dev