name: Our first dbt PR job

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review
  push:
    branches:
      - '!main'

jobs:
  dbt_ci:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }} 
      SNOWFLAKE_DB: ${{ secrets.SNOWFLAKE_DB }}
      SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
      SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.17'
      
      - name: Setup Snowflake key
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY }}" > ~/.dbt/rsa_key.p8
          chmod 600 ~/.dbt/rsa_key.p8

      - name: Install requirements
        run: pip install -r requirements.txt  

      - name: Check connection
        run: dbt debug

      - name: Install dbt dependencies
        run: dbt deps

      - name: dbt build
        run: dbt build #--full-refresh --profiles-dir ./

      - name: Lint models
        run: "sqlfluff lint models"